// Code generated by the Lingua Franca compiler from:
// file://home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/lfvmu/eecs149-final-project/lf-buckler/src-gen/AccelerometerDisplay"
#include "include/ctarget/ctarget.h"
#include "core/reactor.c"
#include "core/mixed_radix.h"
#include "core/port.h"
#include <stdio.h>
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class Accelerometer
// *********** From the preamble, verbatim:
#line 15 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
#include "nrfx_gpiote.h"
#include "nrfx_saadc.h"
#include "buckler.h"        // Defines BUCKLER_ANALOG_ACCEL_...

// ADC channels
#define X_CHANNEL 0
#define Y_CHANNEL 1
#define Z_CHANNEL 2

/**
 * NRF ADC Constants
 * gain is 1/6 and scales the input voltage. 
 * internal reference voltage is 0.6; the voltage range is 0-0.6
 * effective range before gain is 3.6
 * adc resolution is 12 bits; 2^12 = 4096 
 */
 #define FSR 3.6
 #define LSB FSR / 4096

/**
 * ADXL327 Constants.
 * Bias and sensitivity are ratiometric.
 * They are proportional to the supply voltage which might be less than 3V.
 * They can further adjusted using the bias and sensitivity parameters.
 */
#define VSS 2.98
#define ADXL327_BIAS 1.5 * (VSS / 3.0)
#define ADXL327_SENS 0.42 * (VSS / 3.0)

// callback for SAADC events
void saadc_callback (nrfx_saadc_evt_t const * p_event) {
    // Ignore ADC callbacks.
}

// Sample a particular analog channel in blocking mode
nrf_saadc_value_t sample_value(uint8_t channel) {
    nrf_saadc_value_t val;
    ret_code_t error_code = nrfx_saadc_sample_convert(channel, &val);
    APP_ERROR_CHECK(error_code);
    return val;
}

// Global variable to prevent initializing more than once.
bool buckler_accelerometer_initialized = false;

// *********** End of preamble.
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    bool value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} accelerometer_trigger_t;
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    float value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} accelerometer_x_t;
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    float value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} accelerometer_y_t;
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    float value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} accelerometer_z_t;
typedef struct {
    struct self_base_t base;
    #line 67 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    float bias;
    #line 67 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    float sensitivity;
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    accelerometer_trigger_t* _lf_trigger;
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    // width of -2 indicates that it is not a multiport.
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    int _lf_trigger_width;
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    // Default input (in case it does not get connected)
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    accelerometer_trigger_t _lf_default__trigger;
    #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    accelerometer_x_t _lf_x;
    #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    int _lf_x_width;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    accelerometer_y_t _lf_y;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    int _lf_y_width;
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    accelerometer_z_t _lf_z;
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    int _lf_z_width;
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    reaction_t _lf__reaction_0;
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    reaction_t _lf__reaction_1;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    trigger_t _lf__trigger;
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    reaction_t* _lf__trigger_reactions[1];
} accelerometer_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void accelerometerreaction_function_0(void* instance_args) {
    accelerometer_self_t* self = (accelerometer_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    #line 74 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    if (buckler_accelerometer_initialized) return;
    buckler_accelerometer_initialized = true;
    
    // initialize analog to digital converter
    nrfx_saadc_config_t saadc_config = NRFX_SAADC_DEFAULT_CONFIG;
    saadc_config.resolution = NRF_SAADC_RESOLUTION_12BIT;
    ret_code_t error_code = nrfx_saadc_init(&saadc_config, saadc_callback);
    APP_ERROR_CHECK(error_code);
    
    // initialize analog inputs
    // configure with 0 as input pin for now
    nrf_saadc_channel_config_t channel_config = NRFX_SAADC_DEFAULT_CHANNEL_CONFIG_SE(0);
    channel_config.gain = NRF_SAADC_GAIN1_6;
    channel_config.reference = NRF_SAADC_REFERENCE_INTERNAL;
    
    // specify input pin and initialize that ADC channel
    channel_config.pin_p = BUCKLER_ANALOG_ACCEL_X;
    error_code = nrfx_saadc_channel_init(X_CHANNEL, &channel_config);
    APP_ERROR_CHECK(error_code);
    
    // specify input pin and initialize that ADC channel
    channel_config.pin_p = BUCKLER_ANALOG_ACCEL_Y;
    error_code = nrfx_saadc_channel_init(Y_CHANNEL, &channel_config);
    APP_ERROR_CHECK(error_code);
    
    // specify input pin and initialize that ADC channel
    channel_config.pin_p = BUCKLER_ANALOG_ACCEL_Z;
    error_code = nrfx_saadc_channel_init(Z_CHANNEL, &channel_config);
    APP_ERROR_CHECK(error_code);
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void accelerometerreaction_function_1(void* instance_args) {
    accelerometer_self_t* self = (accelerometer_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    accelerometer_trigger_t* trigger = self->_lf_trigger;
    int trigger_width = self->_lf_trigger_width; SUPPRESS_UNUSED_WARNING(trigger_width);
    accelerometer_x_t* x = &self->_lf_x;
    accelerometer_y_t* y = &self->_lf_y;
    accelerometer_z_t* z = &self->_lf_z;
    #line 105 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    nrf_saadc_value_t x_raw, y_raw, z_raw;
    if (trigger->value) {
        // Sample analog inputs.
        x_raw = sample_value(X_CHANNEL);
        y_raw = sample_value(Y_CHANNEL);
        z_raw = sample_value(Z_CHANNEL);
    
        float bias = self->bias + ADXL327_BIAS;
        float sensitivity = self->sensitivity * ADXL327_SENS;
    
        lf_set(x, ((x_raw * LSB) - bias) / sensitivity);
        lf_set(y, ((y_raw * LSB) - bias) / sensitivity);
        lf_set(z, ((z_raw * LSB) - bias) / sensitivity);
    }
}
#include "include/ctarget/set_undef.h"
accelerometer_self_t* new_Accelerometer() {
    accelerometer_self_t* self = (accelerometer_self_t*)_lf_new_reactor(sizeof(accelerometer_self_t));
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    // Set input by default to an always absent default input.
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_trigger = &self->_lf_default__trigger;
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_0.number = 0;
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_0.function = accelerometerreaction_function_0;
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_0.self = self;
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_0.name = "?";
    #line 73 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_1.number = 1;
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_1.function = accelerometerreaction_function_1;
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_1.self = self;
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_1.name = "?";
    #line 104 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__reaction_1.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__trigger.last = NULL;
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__trigger_reactions[0] = &self->_lf__reaction_1;
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__trigger.reactions = &self->_lf__trigger_reactions[0];
    #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf__trigger.number_of_reactions = 1;
    self->_lf__trigger.element_size = sizeof(bool);
    return self;
}
// =============== END reactor class Accelerometer
// =============== START reactor class Display
// *********** From the preamble, verbatim:
#line 14 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
#include "nrfx_gpiote.h"
#include "nrfx_spi.h"

#include "buckler.h"    // Defines BUCKLER_LCD_SCLK, etc.
#include "display.h"    // Defines Buckler display functions and constants.

// Width of the display in characters.
#define BUCKLER_DISPLAY_WIDTH 16

// The SPI instance has to be global for the display to work across functions.
// NOTE: display.h in Buckler library uses legacy nrf drivers rather than nrfx.
// Hence, this type is a legacy type.
nrf_drv_spi_t spi_instance = NRF_DRV_SPI_INSTANCE(1);

// Buffer to use to write messages to the display.
char buckler_message[2][BUCKLER_DISPLAY_WIDTH + 1];

// Flag indicating that SPI has been initialized.
// This is needed so that there can be multiple instances of this reactor.
bool buckler_spi_initialized = false;

// *********** End of preamble.
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    string value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} display_message_t;
typedef struct {
    struct self_base_t base;
    #line 40 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    int row;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    display_message_t* _lf_message;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // width of -2 indicates that it is not a multiport.
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    int _lf_message_width;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // Default input (in case it does not get connected)
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    display_message_t _lf_default__message;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    reaction_t _lf__reaction_0;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    reaction_t _lf__reaction_1;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    trigger_t _lf__message;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    reaction_t* _lf__message_reactions[1];
} display_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void displayreaction_function_0(void* instance_args) {
    display_self_t* self = (display_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    #line 43 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    ret_code_t error_code = NRF_SUCCESS;
    
    if (!buckler_spi_initialized) {
        buckler_spi_initialized = true;
        // initialize spi master
        nrf_drv_spi_config_t spi_config = {
            .sck_pin = BUCKLER_LCD_SCLK,
            .mosi_pin = BUCKLER_LCD_MOSI,
            .miso_pin = BUCKLER_LCD_MISO,
            .ss_pin = BUCKLER_LCD_CS,
            .irq_priority = NRFX_SPI_DEFAULT_CONFIG_IRQ_PRIORITY,
            .orc = 0,
            .frequency = NRF_DRV_SPI_FREQ_4M,
            .mode = NRF_DRV_SPI_MODE_2,
            .bit_order = NRF_DRV_SPI_BIT_ORDER_MSB_FIRST
        };
        error_code = nrf_drv_spi_init(&spi_instance, &spi_config, NULL, NULL);
        APP_ERROR_CHECK(error_code);
    
        // initialize display driver
        error_code = display_init(&spi_instance);
        APP_ERROR_CHECK(error_code);
    
        error_code = display_write("Initialized", 0);
        APP_ERROR_CHECK(error_code);
    }
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void displayreaction_function_1(void* instance_args) {
    display_self_t* self = (display_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    display_message_t* message = self->_lf_message;
    int message_width = self->_lf_message_width; SUPPRESS_UNUSED_WARNING(message_width);
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // Copy the message to the global buffer, truncating it at the display width.
    snprintf(buckler_message[self->row], BUCKLER_DISPLAY_WIDTH + 1, "%s", message->value);
    
    ret_code_t error_code = display_write(buckler_message[self->row], self->row);
    APP_ERROR_CHECK(error_code);
}
#include "include/ctarget/set_undef.h"
display_self_t* new_Display() {
    display_self_t* self = (display_self_t*)_lf_new_reactor(sizeof(display_self_t));
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // Set input by default to an always absent default input.
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf_message = &self->_lf_default__message;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.number = 0;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.function = displayreaction_function_0;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.self = self;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.name = "?";
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.number = 1;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.function = displayreaction_function_1;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.self = self;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.name = "?";
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message.last = NULL;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message_reactions[0] = &self->_lf__reaction_1;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message.reactions = &self->_lf__message_reactions[0];
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message.number_of_reactions = 1;
    self->_lf__message.element_size = sizeof(string);
    return self;
}
// =============== END reactor class Display
// =============== START reactor class AccelerometerDisplay
typedef struct {
    struct self_base_t base;
    #line 25 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    int count;
    struct {
        #line 68 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        accelerometer_trigger_t trigger;
        #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        accelerometer_x_t* x;
        #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        trigger_t x_trigger;
        #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        reaction_t* x_reactions[1];
        #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        accelerometer_z_t* z;
        #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        trigger_t z_trigger;
        #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        reaction_t* z_reactions[1];
        #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        accelerometer_y_t* y;
        #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        trigger_t y_trigger;
        #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
        reaction_t* y_reactions[1];
    } _lf_a;
    int _lf_a_width;
    struct {
        #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
        display_message_t message;
    } _lf_dx;
    int _lf_dx_width;
    struct {
        #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
        display_message_t message;
    } _lf_dy;
    int _lf_dy_width;
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    reaction_t _lf__reaction_0;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    reaction_t _lf__reaction_1;
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    reaction_t _lf__reaction_2;
    #line 23 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    trigger_t _lf__t;
    #line 23 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    reaction_t* _lf__t_reactions[1];
} accelerometerdisplay_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void accelerometerdisplayreaction_function_0(void* instance_args) {
    accelerometerdisplay_self_t* self = (accelerometerdisplay_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct a {
        accelerometer_trigger_t* trigger;
    
    } a;
    a.trigger = &(self->_lf_a.trigger);
    #line 28 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    lf_set(a.trigger, true);
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void accelerometerdisplayreaction_function_1(void* instance_args) {
    accelerometerdisplay_self_t* self = (accelerometerdisplay_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct a {
        accelerometer_x_t* x;
    accelerometer_z_t* z;
    
    } a;
    struct dx {
        display_message_t* message;
    
    } dx;
    a.x = self->_lf_a.x;
    a.z = self->_lf_a.z;
    dx.message = &(self->_lf_dx.message);
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    static char x[BUCKLER_DISPLAY_WIDTH + 1];
    snprintf(x, BUCKLER_DISPLAY_WIDTH + 1, "x:%.2f z:%.2f", a.x->value, a.z->value);
    lf_set(dx.message, x);
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void accelerometerdisplayreaction_function_2(void* instance_args) {
    accelerometerdisplay_self_t* self = (accelerometerdisplay_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct a {
        accelerometer_y_t* y;
    
    } a;
    struct dy {
        display_message_t* message;
    
    } dy;
    a.y = self->_lf_a.y;
    dy.message = &(self->_lf_dy.message);
    #line 36 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    static char y[BUCKLER_DISPLAY_WIDTH + 1];
    snprintf(y, BUCKLER_DISPLAY_WIDTH + 1, "y:%.2f t:%d", a.y->value, (self->count++)/4);
    lf_set(dy.message, y);
}
#include "include/ctarget/set_undef.h"
accelerometerdisplay_self_t* new_AccelerometerDisplay() {
    accelerometerdisplay_self_t* self = (accelerometerdisplay_self_t*)_lf_new_reactor(sizeof(accelerometerdisplay_self_t));
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_a_width = -2;
    #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.x_reactions[0] = &self->_lf__reaction_1;
    #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.x_trigger.reactions = self->_lf_a.x_reactions;
    #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.x_trigger.last = NULL;
    #line 69 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.x_trigger.number_of_reactions = 1;
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.z_reactions[0] = &self->_lf__reaction_1;
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.z_trigger.reactions = self->_lf_a.z_reactions;
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.z_trigger.last = NULL;
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.z_trigger.number_of_reactions = 1;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.y_reactions[0] = &self->_lf__reaction_2;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.y_trigger.reactions = self->_lf_a.y_reactions;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.y_trigger.last = NULL;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Accelerometer.lf"
    self->_lf_a.y_trigger.number_of_reactions = 1;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_dx_width = -2;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_dy_width = -2;
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_0.number = 0;
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_0.function = accelerometerdisplayreaction_function_0;
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_0.self = self;
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_0.name = "?";
    #line 27 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_1.number = 1;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_1.function = accelerometerdisplayreaction_function_1;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_1.self = self;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_1.name = "?";
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_2.number = 2;
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_2.function = accelerometerdisplayreaction_function_2;
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_2.self = self;
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_2.deadline_violation_handler = NULL;
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_2.STP_handler = NULL;
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_2.name = "?";
    #line 35 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__reaction_2.mode = NULL;
    #line 23 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__t.last = NULL;
    #line 23 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    #line 23 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    #line 23 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    #line 23 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/AccelerometerDisplay.lf"
    self->_lf__t.number_of_reactions = 1;
    self->_lf__t.is_timer = true;
    return self;
}
// =============== END reactor class AccelerometerDisplay
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[1];
int _lf_timer_triggers_size = 1;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[3];
int _lf_startup_reactions_size = 3;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 6;
    _lf_is_present_fields = (bool**)calloc(6, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(6, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int _lf_tokens_with_ref_count_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_tokens_with_ref_count_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    accelerometerdisplay_self_t* accelerometerdisplay_self[1];
    SUPPRESS_UNUSED_WARNING(accelerometerdisplay_self);
    accelerometer_self_t* accelerometerdisplay_a_self[1];
    SUPPRESS_UNUSED_WARNING(accelerometerdisplay_a_self);
    display_self_t* accelerometerdisplay_dx_self[1];
    SUPPRESS_UNUSED_WARNING(accelerometerdisplay_dx_self);
    display_self_t* accelerometerdisplay_dy_self[1];
    SUPPRESS_UNUSED_WARNING(accelerometerdisplay_dy_self);
    // ***** Start initializing AccelerometerDisplay of class AccelerometerDisplay
    accelerometerdisplay_self[0] = new_AccelerometerDisplay();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    { // For scoping
        static int _initial = 0;
        accelerometerdisplay_self[0]->count = _initial;
    } // End scoping.
    // Initializing timer AccelerometerDisplay.t.
    accelerometerdisplay_self[0]->_lf__t.offset = 0;
    accelerometerdisplay_self[0]->_lf__t.period = MSEC(250);
    _lf_timer_triggers[_lf_timer_triggers_count++] = &accelerometerdisplay_self[0]->_lf__t;
    accelerometerdisplay_self[0]->_lf__t.mode = NULL;
    accelerometerdisplay_self[0]->_lf__reaction_0.deadline = NEVER;
    accelerometerdisplay_self[0]->_lf__reaction_1.deadline = NEVER;
    accelerometerdisplay_self[0]->_lf__reaction_2.deadline = NEVER;
    {
        // ***** Start initializing AccelerometerDisplay.a of class Accelerometer
        accelerometerdisplay_a_self[0] = new_Accelerometer();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        accelerometerdisplay_a_self[0]->bias = 0.0;
        accelerometerdisplay_a_self[0]->sensitivity = 1.0;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_x_width = -2;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_y_width = -2;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_z_width = -2;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_trigger_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &accelerometerdisplay_a_self[0]->_lf__reaction_0;
        accelerometerdisplay_a_self[0]->_lf__reaction_0.deadline = NEVER;
        accelerometerdisplay_a_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing AccelerometerDisplay.a
    }
    {
        // ***** Start initializing AccelerometerDisplay.dx of class Display
        accelerometerdisplay_dx_self[0] = new_Display();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        accelerometerdisplay_dx_self[0]->row = 0;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_dx_self[0]->_lf_message_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &accelerometerdisplay_dx_self[0]->_lf__reaction_0;
        accelerometerdisplay_dx_self[0]->_lf__reaction_0.deadline = NEVER;
        accelerometerdisplay_dx_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing AccelerometerDisplay.dx
    }
    {
        // ***** Start initializing AccelerometerDisplay.dy of class Display
        accelerometerdisplay_dy_self[0] = new_Display();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        accelerometerdisplay_dy_self[0]->row = 1;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_dy_self[0]->_lf_message_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &accelerometerdisplay_dy_self[0]->_lf__reaction_0;
        accelerometerdisplay_dy_self[0]->_lf__reaction_0.deadline = NEVER;
        accelerometerdisplay_dy_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing AccelerometerDisplay.dy
    }
    //***** End initializing AccelerometerDisplay
    // **** Start deferred initialize for AccelerometerDisplay
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of AccelerometerDisplay.
        accelerometerdisplay_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        accelerometerdisplay_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &accelerometerdisplay_self[0]->base.allocations);
        accelerometerdisplay_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &accelerometerdisplay_self[0]->base.allocations);
        accelerometerdisplay_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &accelerometerdisplay_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                accelerometerdisplay_self[0]->_lf__reaction_0.output_produced[count++] = &accelerometerdisplay_self[0]->_lf_a.trigger.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of AccelerometerDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of AccelerometerDisplay.
        accelerometerdisplay_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        accelerometerdisplay_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &accelerometerdisplay_self[0]->base.allocations);
        accelerometerdisplay_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &accelerometerdisplay_self[0]->base.allocations);
        accelerometerdisplay_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &accelerometerdisplay_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                accelerometerdisplay_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_self[0]->_lf_dx.message.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of AccelerometerDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of AccelerometerDisplay.
        accelerometerdisplay_self[0]->_lf__reaction_2.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        accelerometerdisplay_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &accelerometerdisplay_self[0]->base.allocations);
        accelerometerdisplay_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &accelerometerdisplay_self[0]->base.allocations);
        accelerometerdisplay_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &accelerometerdisplay_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                accelerometerdisplay_self[0]->_lf__reaction_2.output_produced[count++] = &accelerometerdisplay_self[0]->_lf_dy.message.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of AccelerometerDisplay
        // **** Start deferred initialize for AccelerometerDisplay.a
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of AccelerometerDisplay.a.
            accelerometerdisplay_a_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of AccelerometerDisplay.a
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of AccelerometerDisplay.a.
            accelerometerdisplay_a_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            accelerometerdisplay_a_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    3, sizeof(trigger_t**),
                    &accelerometerdisplay_a_self[0]->base.allocations);
            accelerometerdisplay_a_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    3, sizeof(int),
                    &accelerometerdisplay_a_self[0]->base.allocations);
            accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    3, sizeof(bool*),
                    &accelerometerdisplay_a_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_a_self[0]->_lf_x.is_present;
                }
                {
                    accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_a_self[0]->_lf_y.is_present;
                }
                {
                    accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_a_self[0]->_lf_z.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of AccelerometerDisplay.a
        }
        // **** End of deferred initialize for AccelerometerDisplay.a
        // **** Start deferred initialize for AccelerometerDisplay.dx
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of AccelerometerDisplay.dx.
            accelerometerdisplay_dx_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of AccelerometerDisplay.dx
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of AccelerometerDisplay.dx.
            accelerometerdisplay_dx_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of AccelerometerDisplay.dx
        }
        // **** End of deferred initialize for AccelerometerDisplay.dx
        // **** Start deferred initialize for AccelerometerDisplay.dy
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of AccelerometerDisplay.dy.
            accelerometerdisplay_dy_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of AccelerometerDisplay.dy
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of AccelerometerDisplay.dy.
            accelerometerdisplay_dy_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of AccelerometerDisplay.dy
        }
        // **** End of deferred initialize for AccelerometerDisplay.dy
    }
    // **** End of deferred initialize for AccelerometerDisplay
    // **** Start non-nested deferred initialize for AccelerometerDisplay
    // For reference counting, set num_destinations for port a.trigger.
    // Iterate over range AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        accelerometerdisplay_self[src_runtime]->_lf_a.trigger.num_destinations = 1;
    }
    // For reference counting, set num_destinations for port dx.message.
    // Iterate over range AccelerometerDisplay.dx.message(0,1)->[AccelerometerDisplay.dx.message(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        accelerometerdisplay_self[src_runtime]->_lf_dx.message.num_destinations = 1;
    }
    // For reference counting, set num_destinations for port dy.message.
    // Iterate over range AccelerometerDisplay.dy.message(0,1)->[AccelerometerDisplay.dy.message(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        accelerometerdisplay_self[src_runtime]->_lf_dy.message.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of AccelerometerDisplay triggers 1 downstream reactions
            // through port AccelerometerDisplay.a.trigger.
            accelerometerdisplay_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of AccelerometerDisplay, allocate an
            // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.trigger
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &accelerometerdisplay_self[src_runtime]->base.allocations); 
            accelerometerdisplay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)] and AccelerometerDisplay.a.trigger(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range AccelerometerDisplay.a.trigger(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port AccelerometerDisplay.a.trigger's trigger struct.
                accelerometerdisplay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_a_self[dst_runtime]->_lf__trigger;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range AccelerometerDisplay.dx.message(0,1)->[AccelerometerDisplay.dx.message(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of AccelerometerDisplay triggers 1 downstream reactions
            // through port AccelerometerDisplay.dx.message.
            accelerometerdisplay_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of AccelerometerDisplay, allocate an
            // array of trigger pointers for downstream reactions through port AccelerometerDisplay.dx.message
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &accelerometerdisplay_self[src_runtime]->base.allocations); 
            accelerometerdisplay_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges AccelerometerDisplay.dx.message(0,1)->[AccelerometerDisplay.dx.message(0,1)] and AccelerometerDisplay.dx.message(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range AccelerometerDisplay.dx.message(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port AccelerometerDisplay.dx.message's trigger struct.
                accelerometerdisplay_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_dx_self[dst_runtime]->_lf__message;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range AccelerometerDisplay.dy.message(0,1)->[AccelerometerDisplay.dy.message(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of AccelerometerDisplay triggers 1 downstream reactions
            // through port AccelerometerDisplay.dy.message.
            accelerometerdisplay_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of AccelerometerDisplay, allocate an
            // array of trigger pointers for downstream reactions through port AccelerometerDisplay.dy.message
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &accelerometerdisplay_self[src_runtime]->base.allocations); 
            accelerometerdisplay_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges AccelerometerDisplay.dy.message(0,1)->[AccelerometerDisplay.dy.message(0,1)] and AccelerometerDisplay.dy.message(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range AccelerometerDisplay.dy.message(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port AccelerometerDisplay.dy.message's trigger struct.
                accelerometerdisplay_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_dy_self[dst_runtime]->_lf__message;
            }
        }
    }
    // **** Start non-nested deferred initialize for AccelerometerDisplay.a
    // For reference counting, set num_destinations for port AccelerometerDisplay.a.x.
    // Iterate over range AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        accelerometerdisplay_a_self[src_runtime]->_lf_x.num_destinations = 1;
    }
    // For reference counting, set num_destinations for port AccelerometerDisplay.a.y.
    // Iterate over range AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        accelerometerdisplay_a_self[src_runtime]->_lf_y.num_destinations = 1;
    }
    // For reference counting, set num_destinations for port AccelerometerDisplay.a.z.
    // Iterate over range AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        accelerometerdisplay_a_self[src_runtime]->_lf_z.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of AccelerometerDisplay.a triggers 1 downstream reactions
            // through port AccelerometerDisplay.a.x.
            accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of AccelerometerDisplay.a, allocate an
            // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.x
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &accelerometerdisplay_a_self[src_runtime]->base.allocations); 
            accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of AccelerometerDisplay.a triggers 1 downstream reactions
            // through port AccelerometerDisplay.a.y.
            accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of AccelerometerDisplay.a, allocate an
            // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.y
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &accelerometerdisplay_a_self[src_runtime]->base.allocations); 
            accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        // Iterate over range AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of AccelerometerDisplay.a triggers 1 downstream reactions
            // through port AccelerometerDisplay.a.z.
            accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of AccelerometerDisplay.a, allocate an
            // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.z
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &accelerometerdisplay_a_self[src_runtime]->base.allocations); 
            accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)] and AccelerometerDisplay.a.x(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range AccelerometerDisplay.a.x(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port AccelerometerDisplay.a.x has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_self[dst_runtime]->_lf_a.x_trigger;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 1;
        // Iterate over ranges AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)] and AccelerometerDisplay.a.y(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range AccelerometerDisplay.a.y(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port AccelerometerDisplay.a.y has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_self[dst_runtime]->_lf_a.y_trigger;
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 2;
        // Iterate over ranges AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)] and AccelerometerDisplay.a.z(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range AccelerometerDisplay.a.z(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Port AccelerometerDisplay.a.z has reactions in its parent's parent.
                // Point to the trigger struct for those reactions.
                accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_self[dst_runtime]->_lf_a.z_trigger;
            }
        }
    }
    // **** End of non-nested deferred initialize for AccelerometerDisplay.a
    // **** Start non-nested deferred initialize for AccelerometerDisplay.dx
    // **** End of non-nested deferred initialize for AccelerometerDisplay.dx
    // **** Start non-nested deferred initialize for AccelerometerDisplay.dy
    // **** End of non-nested deferred initialize for AccelerometerDisplay.dy
    // **** End of non-nested deferred initialize for AccelerometerDisplay
    // Connect inputs and outputs for reactor AccelerometerDisplay.
    // Connect inputs and outputs for reactor AccelerometerDisplay.a.
    // Connect AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)] to port AccelerometerDisplay.a.trigger(0,1)
    // Iterate over ranges AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)] and AccelerometerDisplay.a.trigger(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.trigger(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_a_self[dst_runtime]->_lf_trigger = (accelerometer_trigger_t*)&accelerometerdisplay_self[src_runtime]->_lf_a.trigger;
        }
    }
    // Connect AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)] to port AccelerometerDisplay.a.x(0,1)
    // Iterate over ranges AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)] and AccelerometerDisplay.a.x(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.x(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_self[dst_runtime]->_lf_a.x = (accelerometer_x_t*)&accelerometerdisplay_a_self[src_runtime]->_lf_x;
        }
    }
    // Connect AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)] to port AccelerometerDisplay.a.y(0,1)
    // Iterate over ranges AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)] and AccelerometerDisplay.a.y(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.y(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_self[dst_runtime]->_lf_a.y = (accelerometer_y_t*)&accelerometerdisplay_a_self[src_runtime]->_lf_y;
        }
    }
    // Connect AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)] to port AccelerometerDisplay.a.z(0,1)
    // Iterate over ranges AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)] and AccelerometerDisplay.a.z(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.z(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_self[dst_runtime]->_lf_a.z = (accelerometer_z_t*)&accelerometerdisplay_a_self[src_runtime]->_lf_z;
        }
    }
    // Connect inputs and outputs for reactor AccelerometerDisplay.dx.
    // Connect AccelerometerDisplay.dx.message(0,1)->[AccelerometerDisplay.dx.message(0,1)] to port AccelerometerDisplay.dx.message(0,1)
    // Iterate over ranges AccelerometerDisplay.dx.message(0,1)->[AccelerometerDisplay.dx.message(0,1)] and AccelerometerDisplay.dx.message(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.dx.message(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_dx_self[dst_runtime]->_lf_message = (display_message_t*)&accelerometerdisplay_self[src_runtime]->_lf_dx.message;
        }
    }
    // Connect inputs and outputs for reactor AccelerometerDisplay.dy.
    // Connect AccelerometerDisplay.dy.message(0,1)->[AccelerometerDisplay.dy.message(0,1)] to port AccelerometerDisplay.dy.message(0,1)
    // Iterate over ranges AccelerometerDisplay.dy.message(0,1)->[AccelerometerDisplay.dy.message(0,1)] and AccelerometerDisplay.dy.message(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.dy.message(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_dy_self[dst_runtime]->_lf_message = (display_message_t*)&accelerometerdisplay_self[src_runtime]->_lf_dy.message;
        }
    }
    {
    }
    {
    }
    {
    }
    // Add port AccelerometerDisplay.a.trigger to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &accelerometerdisplay_self[0]->_lf_a.trigger.is_present;
                count++;
            }
        }
    }
    // Add port AccelerometerDisplay.dx.message to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[1 + count] = &accelerometerdisplay_self[0]->_lf_dx.message.is_present;
                count++;
            }
        }
    }
    // Add port AccelerometerDisplay.dy.message to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[2 + count] = &accelerometerdisplay_self[0]->_lf_dy.message.is_present;
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port AccelerometerDisplay.a.x to array of is_present fields.
            _lf_is_present_fields[3 + count] = &accelerometerdisplay_a_self[0]->_lf_x.is_present;
            count++;
            // Add port AccelerometerDisplay.a.y to array of is_present fields.
            _lf_is_present_fields[3 + count] = &accelerometerdisplay_a_self[0]->_lf_y.is_present;
            count++;
            // Add port AccelerometerDisplay.a.z to array of is_present fields.
            _lf_is_present_fields[3 + count] = &accelerometerdisplay_a_self[0]->_lf_z.is_present;
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance AccelerometerDisplay
    {
        accelerometerdisplay_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        accelerometerdisplay_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        accelerometerdisplay_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 2 and 
        // deadline 140737488355327 shifted left 16 bits.
        accelerometerdisplay_self[0]->_lf__reaction_1.index = 0x7fffffffffff0002LL;
        accelerometerdisplay_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 3 and 
        // deadline 140737488355327 shifted left 16 bits.
        accelerometerdisplay_self[0]->_lf__reaction_2.index = 0x7fffffffffff0003LL;
        // Set reaction priorities for ReactorInstance AccelerometerDisplay.a
        {
            accelerometerdisplay_a_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            accelerometerdisplay_a_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            accelerometerdisplay_a_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            accelerometerdisplay_a_self[0]->_lf__reaction_1.index = 0x7fffffffffff0001LL;
        }
        // Set reaction priorities for ReactorInstance AccelerometerDisplay.dx
        {
            accelerometerdisplay_dx_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            accelerometerdisplay_dx_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            accelerometerdisplay_dx_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 140737488355327 shifted left 16 bits.
            accelerometerdisplay_dx_self[0]->_lf__reaction_1.index = 0x7fffffffffff0003LL;
        }
        // Set reaction priorities for ReactorInstance AccelerometerDisplay.dy
        {
            accelerometerdisplay_dy_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            accelerometerdisplay_dy_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            accelerometerdisplay_dy_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 140737488355327 shifted left 16 bits.
            accelerometerdisplay_dy_self[0]->_lf__reaction_1.index = 0x7fffffffffff0004LL;
        }
    }
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }

}
void logical_tag_complete(tag_t tag_to_send) {

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
void terminate_execution() {}
