// Code generated by the Lingua Franca compiler from:
// file://home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/lfvmu/eecs149-final-project/lf-buckler/src-gen/RobotSensor"
#include "include/ctarget/ctarget.h"
#include "core/reactor.c"
#include "core/mixed_radix.h"
#include "core/port.h"
#include "lib/romi.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class RobotSensor
typedef struct {
    struct self_base_t base;
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    reaction_t _lf__reaction_0;
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    reaction_t _lf__reaction_1;
    #line 11 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    trigger_t _lf__t;
    #line 11 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    reaction_t* _lf__t_reactions[1];
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
} robotsensor_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void robotsensorreaction_function_0(void* instance_args) {
    robotsensor_self_t* self = (robotsensor_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    #line 13 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    // Initialize the robot.
    APP_ERROR_CHECK(romi_init());
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void robotsensorreaction_function_1(void* instance_args) {
    robotsensor_self_t* self = (robotsensor_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    #line 17 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    romi_sensors_t sensors;
    APP_ERROR_CHECK(romi_sensors_poll(&sensors));
    // print results
    printf("\n");
    printf("### Romi Sensor Values at index %d ###\n", sensors.time_stamp);
    printf("Bump left:\t%d\n", sensors.bumps.left);
    printf("Bump center:\t%d\n", sensors.bumps.center);
    printf("Bump right:\t%d\n", sensors.bumps.right);
    printf("\n");
    printf("Reflectance left:\t%d\n", sensors.reflectance.left);
    printf("Reflectance center:\t%d\n", sensors.reflectance.center);
    printf("Reflectance right:\t%d\n", sensors.reflectance.right);
    printf("\n");
    printf("Button left:\t%d\n", sensors.buttons.left);
    printf("Button right:\t%d\n", sensors.buttons.right);
    printf("\n");
    printf("Encoder left:\t%d\n", sensors.encoders.left);
    printf("Encoder right\t%d\n", sensors.encoders.right);
}
#include "include/ctarget/set_undef.h"
robotsensor_self_t* new_RobotSensor() {
    robotsensor_self_t* self = (robotsensor_self_t*)_lf_new_reactor(sizeof(robotsensor_self_t));
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_0.number = 0;
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_0.function = robotsensorreaction_function_0;
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_0.self = self;
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_0.name = "?";
    #line 12 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_1.number = 1;
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_1.function = robotsensorreaction_function_1;
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_1.self = self;
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_1.name = "?";
    #line 16 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 11 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__t.last = NULL;
    #line 11 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    #line 11 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__t_reactions[0] = &self->_lf__reaction_1;
    #line 11 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    #line 11 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotSensor.lf"
    self->_lf__t.number_of_reactions = 1;
    self->_lf__t.is_timer = true;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    return self;
}
// =============== END reactor class RobotSensor
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[1];
int _lf_timer_triggers_size = 1;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int _lf_tokens_with_ref_count_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_tokens_with_ref_count_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    robotsensor_self_t* robotsensor_self[1];
    SUPPRESS_UNUSED_WARNING(robotsensor_self);
    // ***** Start initializing RobotSensor of class RobotSensor
    robotsensor_self[0] = new_RobotSensor();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    _lf_startup_reactions[_lf_startup_reactions_count++] = &robotsensor_self[0]->_lf__reaction_0;
    // Initializing timer RobotSensor.t.
    robotsensor_self[0]->_lf__t.offset = 0;
    robotsensor_self[0]->_lf__t.period = MSEC(100);
    _lf_timer_triggers[_lf_timer_triggers_count++] = &robotsensor_self[0]->_lf__t;
    robotsensor_self[0]->_lf__t.mode = NULL;
    robotsensor_self[0]->_lf__reaction_0.deadline = NEVER;
    robotsensor_self[0]->_lf__reaction_1.deadline = NEVER;
    //***** End initializing RobotSensor
    // **** Start deferred initialize for RobotSensor
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of RobotSensor.
        robotsensor_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of RobotSensor
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of RobotSensor.
        robotsensor_self[0]->_lf__reaction_1.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 1 of RobotSensor
    }
    // **** End of deferred initialize for RobotSensor
    // **** Start non-nested deferred initialize for RobotSensor
    // **** End of non-nested deferred initialize for RobotSensor
    // Connect inputs and outputs for reactor RobotSensor.
    // Set reaction priorities for ReactorInstance RobotSensor
    {
        robotsensor_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        robotsensor_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        robotsensor_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 1 and 
        // deadline 140737488355327 shifted left 16 bits.
        robotsensor_self[0]->_lf__reaction_1.index = 0x7fffffffffff0001LL;
    }
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }

}
void logical_tag_complete(tag_t tag_to_send) {

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
void terminate_execution() {}
