// Code generated by the Lingua Franca compiler from:
// file://home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/lfvmu/eecs149-final-project/lf-buckler/src-gen/RobotTemplate"
#define MODAL_REACTORS
#include "include/ctarget/ctarget.h"
#include "core/reactor.c"
#include "core/mixed_radix.h"
#include "core/port.h"
// Include the functions for driving the robot
// and reading its sensors.
#include "lib/romi.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class Robot
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    bool value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} robot_drive_t;
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    string value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} robot_notify_t;
typedef struct {
    struct self_base_t base;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    robot_drive_t* _lf_drive;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    // width of -2 indicates that it is not a multiport.
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    int _lf_drive_width;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    // Default input (in case it does not get connected)
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    robot_drive_t _lf_default__drive;
    #line 22 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    robot_notify_t _lf_notify;
    #line 22 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    int _lf_notify_width;
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    reaction_t _lf__reaction_0;
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    reaction_t _lf__reaction_1;
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    reaction_t _lf__reaction_2;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    trigger_t _lf__drive;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    reaction_t* _lf__drive_reactions[2];
    reactor_mode_t _lf__modes[2];
} robot_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void robotreaction_function_0(void* instance_args) {
    robot_self_t* self = (robot_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    robot_notify_t* notify = &self->_lf_notify;
    #line 25 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    // Initialize the robot.
    APP_ERROR_CHECK(romi_init());
    lf_set(notify, "INIT");
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void robotreaction_function_1(void* instance_args) {
    robot_self_t* self = (robot_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    robot_drive_t* drive = self->_lf_drive;
    int drive_width = self->_lf_drive_width; SUPPRESS_UNUSED_WARNING(drive_width);
    reactor_mode_t* DRIVING = &self->_lf__modes[1];
    lf_mode_change_type_t _lf_DRIVING_change_type = reset_transition;
    robot_notify_t* notify = &self->_lf_notify;
    #line 32 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    lf_set_mode(DRIVING);
    lf_set(notify, "DRIVING");
    romi_drive_direct(100, 100);
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void robotreaction_function_2(void* instance_args) {
    robot_self_t* self = (robot_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    robot_drive_t* drive = self->_lf_drive;
    int drive_width = self->_lf_drive_width; SUPPRESS_UNUSED_WARNING(drive_width);
    reactor_mode_t* STOPPED = &self->_lf__modes[0];
    lf_mode_change_type_t _lf_STOPPED_change_type = reset_transition;
    robot_notify_t* notify = &self->_lf_notify;
    #line 40 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    lf_set_mode(STOPPED);
    lf_set(notify, "STOPPED");
    romi_drive_direct(0, 0);
}
#include "include/ctarget/set_undef.h"
robot_self_t* new_Robot() {
    robot_self_t* self = (robot_self_t*)_lf_new_reactor(sizeof(robot_self_t));
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    // Set input by default to an always absent default input.
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf_drive = &self->_lf_default__drive;
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.number = 0;
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.function = robotreaction_function_0;
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.self = self;
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.name = "?";
    #line 24 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_1.number = 1;
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_1.function = robotreaction_function_1;
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_1.self = self;
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_1.name = "?";
    #line 31 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_1.mode = &self->_lf__modes[0];
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_2.number = 2;
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_2.function = robotreaction_function_2;
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_2.self = self;
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_2.deadline_violation_handler = NULL;
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_2.STP_handler = NULL;
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_2.name = "?";
    #line 39 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_2.mode = &self->_lf__modes[1];
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__drive.last = NULL;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__drive_reactions[0] = &self->_lf__reaction_1;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__drive_reactions[1] = &self->_lf__reaction_2;
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__drive.reactions = &self->_lf__drive_reactions[0];
    #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__drive.number_of_reactions = 2;
    self->_lf__drive.element_size = sizeof(bool);
    // Initialize modes
    self_base_t* _lf_self_base = (self_base_t*)self;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[0].state = &_lf_self_base->_lf__mode_state;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[0].name = "STOPPED";
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[0].deactivation_time = 0;
    #line 30 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[0].flags = 0;
    #line 38 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[1].state = &_lf_self_base->_lf__mode_state;
    #line 38 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[1].name = "DRIVING";
    #line 38 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[1].deactivation_time = 0;
    #line 38 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__modes[1].flags = 0;
    // Initialize mode state
    _lf_self_base->_lf__mode_state.parent_mode = NULL;
    _lf_self_base->_lf__mode_state.initial_mode = &self->_lf__modes[0];
    _lf_self_base->_lf__mode_state.current_mode = _lf_self_base->_lf__mode_state.initial_mode;
    _lf_self_base->_lf__mode_state.next_mode = NULL;
    _lf_self_base->_lf__mode_state.mode_change = no_transition;
    return self;
}
// =============== END reactor class Robot
// =============== START reactor class Display
// *********** From the preamble, verbatim:
#line 14 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
#include "nrfx_gpiote.h"
#include "nrfx_spi.h"

#include "buckler.h"    // Defines BUCKLER_LCD_SCLK, etc.
#include "display.h"    // Defines Buckler display functions and constants.

// Width of the display in characters.
#define BUCKLER_DISPLAY_WIDTH 16

// The SPI instance has to be global for the display to work across functions.
// NOTE: display.h in Buckler library uses legacy nrf drivers rather than nrfx.
// Hence, this type is a legacy type.
nrf_drv_spi_t spi_instance = NRF_DRV_SPI_INSTANCE(1);

// Buffer to use to write messages to the display.
char buckler_message[2][BUCKLER_DISPLAY_WIDTH + 1];

// Flag indicating that SPI has been initialized.
// This is needed so that there can be multiple instances of this reactor.
bool buckler_spi_initialized = false;

// *********** End of preamble.
typedef struct {
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    string value;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} display_message_t;
typedef struct {
    struct self_base_t base;
    #line 40 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    int row;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    display_message_t* _lf_message;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // width of -2 indicates that it is not a multiport.
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    int _lf_message_width;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // Default input (in case it does not get connected)
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    display_message_t _lf_default__message;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    reaction_t _lf__reaction_0;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    reaction_t _lf__reaction_1;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    trigger_t _lf__message;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    reaction_t* _lf__message_reactions[1];
} display_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void displayreaction_function_0(void* instance_args) {
    display_self_t* self = (display_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    #line 43 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    ret_code_t error_code = NRF_SUCCESS;
    
    if (!buckler_spi_initialized) {
        buckler_spi_initialized = true;
        // initialize spi master
        nrf_drv_spi_config_t spi_config = {
            .sck_pin = BUCKLER_LCD_SCLK,
            .mosi_pin = BUCKLER_LCD_MOSI,
            .miso_pin = BUCKLER_LCD_MISO,
            .ss_pin = BUCKLER_LCD_CS,
            .irq_priority = NRFX_SPI_DEFAULT_CONFIG_IRQ_PRIORITY,
            .orc = 0,
            .frequency = NRF_DRV_SPI_FREQ_4M,
            .mode = NRF_DRV_SPI_MODE_2,
            .bit_order = NRF_DRV_SPI_BIT_ORDER_MSB_FIRST
        };
        error_code = nrf_drv_spi_init(&spi_instance, &spi_config, NULL, NULL);
        APP_ERROR_CHECK(error_code);
    
        // initialize display driver
        error_code = display_init(&spi_instance);
        APP_ERROR_CHECK(error_code);
    
        error_code = display_write("Initialized", 0);
        APP_ERROR_CHECK(error_code);
    }
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void displayreaction_function_1(void* instance_args) {
    display_self_t* self = (display_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    display_message_t* message = self->_lf_message;
    int message_width = self->_lf_message_width; SUPPRESS_UNUSED_WARNING(message_width);
    #line 71 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // Copy the message to the global buffer, truncating it at the display width.
    snprintf(buckler_message[self->row], BUCKLER_DISPLAY_WIDTH + 1, "%s", message->value);
    
    ret_code_t error_code = display_write(buckler_message[self->row], self->row);
    APP_ERROR_CHECK(error_code);
}
#include "include/ctarget/set_undef.h"
display_self_t* new_Display() {
    display_self_t* self = (display_self_t*)_lf_new_reactor(sizeof(display_self_t));
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    // Set input by default to an always absent default input.
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf_message = &self->_lf_default__message;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.number = 0;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.function = displayreaction_function_0;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.self = self;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.name = "?";
    #line 42 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.number = 1;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.function = displayreaction_function_1;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.self = self;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.name = "?";
    #line 70 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__reaction_1.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message.last = NULL;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message_reactions[0] = &self->_lf__reaction_1;
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message.reactions = &self->_lf__message_reactions[0];
    #line 41 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/lib/Display.lf"
    self->_lf__message.number_of_reactions = 1;
    self->_lf__message.element_size = sizeof(string);
    return self;
}
// =============== END reactor class Display
// =============== START reactor class RobotTemplate
typedef struct {
    struct self_base_t base;
    #line 49 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    bool drive;
    struct {
        #line 21 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
        robot_drive_t drive;
    } _lf_robot;
    int _lf_robot_width;
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    reaction_t _lf__reaction_0;
    #line 48 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    trigger_t _lf__t;
    #line 48 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    reaction_t* _lf__t_reactions[1];
} robottemplate_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void robottemplatereaction_function_0(void* instance_args) {
    robottemplate_self_t* self = (robottemplate_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct robot {
        robot_drive_t* drive;
    
    } robot;
    robot.drive = &(self->_lf_robot.drive);
    #line 53 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    SET(robot.drive, self->drive);
    // Toggle the drive state variable for next time.
    self->drive = !self->drive;
}
#include "include/ctarget/set_undef.h"
robottemplate_self_t* new_RobotTemplate() {
    robottemplate_self_t* self = (robottemplate_self_t*)_lf_new_reactor(sizeof(robottemplate_self_t));
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_robot_width = -2;
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.number = 0;
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.function = robottemplatereaction_function_0;
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.self = self;
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.name = "?";
    #line 52 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 48 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__t.last = NULL;
    #line 48 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    #line 48 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    #line 48 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    #line 48 "file:/home/lfvmu/eecs149-final-project/lf-buckler/src/RobotTemplate.lf"
    self->_lf__t.number_of_reactions = 1;
    self->_lf__t.is_timer = true;
    return self;
}
// =============== END reactor class RobotTemplate
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[1];
int _lf_timer_triggers_size = 1;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[2];
int _lf_startup_reactions_size = 2;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
// Array of pointers to mode states to be handled in _lf_handle_mode_changes().
reactor_mode_state_t* _lf_modal_reactor_states[1];
int _lf_modal_reactor_states_size = 1;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 2;
    _lf_is_present_fields = (bool**)calloc(2, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(2, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int _lf_tokens_with_ref_count_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_tokens_with_ref_count_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int _lf_modal_reactor_states_count = 0;
    int _lf_modal_state_reset_count = 0;
    robottemplate_self_t* robottemplate_self[1];
    SUPPRESS_UNUSED_WARNING(robottemplate_self);
    robot_self_t* robottemplate_robot_self[1];
    SUPPRESS_UNUSED_WARNING(robottemplate_robot_self);
    display_self_t* robottemplate_display_self[1];
    SUPPRESS_UNUSED_WARNING(robottemplate_display_self);
    // ***** Start initializing RobotTemplate of class RobotTemplate
    robottemplate_self[0] = new_RobotTemplate();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    { // For scoping
        static bool _initial = false;
        robottemplate_self[0]->drive = _initial;
    } // End scoping.
    // Initializing timer RobotTemplate.t.
    robottemplate_self[0]->_lf__t.offset = 0;
    robottemplate_self[0]->_lf__t.period = SEC(4);
    _lf_timer_triggers[_lf_timer_triggers_count++] = &robottemplate_self[0]->_lf__t;
    robottemplate_self[0]->_lf__t.mode = NULL;
    robottemplate_self[0]->_lf__reaction_0.deadline = NEVER;
    {
        // ***** Start initializing RobotTemplate.robot of class Robot
        robottemplate_robot_self[0] = new_Robot();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        robottemplate_robot_self[0]->_lf_notify_width = -2;
        // width of -2 indicates that it is not a multiport.
        robottemplate_robot_self[0]->_lf_drive_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &robottemplate_robot_self[0]->_lf__reaction_0;
        robottemplate_robot_self[0]->_lf__reaction_0.deadline = NEVER;
        robottemplate_robot_self[0]->_lf__reaction_1.deadline = NEVER;
        robottemplate_robot_self[0]->_lf__reaction_2.deadline = NEVER;
        // Register for transition handling
        _lf_modal_reactor_states[_lf_modal_reactor_states_count++] = &((self_base_t*)robottemplate_robot_self[0])->_lf__mode_state;
        //***** End initializing RobotTemplate.robot
    }
    {
        // ***** Start initializing RobotTemplate.display of class Display
        robottemplate_display_self[0] = new_Display();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        robottemplate_display_self[0]->row = 0;
        // width of -2 indicates that it is not a multiport.
        robottemplate_display_self[0]->_lf_message_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &robottemplate_display_self[0]->_lf__reaction_0;
        robottemplate_display_self[0]->_lf__reaction_0.deadline = NEVER;
        robottemplate_display_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing RobotTemplate.display
    }
    //***** End initializing RobotTemplate
    // **** Start deferred initialize for RobotTemplate
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of RobotTemplate.
        robottemplate_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        robottemplate_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &robottemplate_self[0]->base.allocations);
        robottemplate_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &robottemplate_self[0]->base.allocations);
        robottemplate_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &robottemplate_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                robottemplate_self[0]->_lf__reaction_0.output_produced[count++] = &robottemplate_self[0]->_lf_robot.drive.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of RobotTemplate
        // **** Start deferred initialize for RobotTemplate.robot
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of RobotTemplate.robot.
            robottemplate_robot_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robottemplate_robot_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &robottemplate_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robottemplate_robot_self[0]->_lf__reaction_0.output_produced[count++] = &robottemplate_robot_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of RobotTemplate.robot
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotTemplate.robot.
            robottemplate_robot_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robottemplate_robot_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &robottemplate_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robottemplate_robot_self[0]->_lf__reaction_1.output_produced[count++] = &robottemplate_robot_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of RobotTemplate.robot
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of RobotTemplate.robot.
            robottemplate_robot_self[0]->_lf__reaction_2.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            robottemplate_robot_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &robottemplate_robot_self[0]->base.allocations);
            robottemplate_robot_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &robottemplate_robot_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    robottemplate_robot_self[0]->_lf__reaction_2.output_produced[count++] = &robottemplate_robot_self[0]->_lf_notify.is_present;
                }
            }
            
            // ** End initialization for reaction 2 of RobotTemplate.robot
        }
        // **** End of deferred initialize for RobotTemplate.robot
        // **** Start deferred initialize for RobotTemplate.display
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of RobotTemplate.display.
            robottemplate_display_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of RobotTemplate.display
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of RobotTemplate.display.
            robottemplate_display_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of RobotTemplate.display
        }
        // **** End of deferred initialize for RobotTemplate.display
    }
    // **** End of deferred initialize for RobotTemplate
    // **** Start non-nested deferred initialize for RobotTemplate
    // For reference counting, set num_destinations for port robot.drive.
    // Iterate over range RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        robottemplate_self[src_runtime]->_lf_robot.drive.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of RobotTemplate triggers 1 downstream reactions
            // through port RobotTemplate.robot.drive.
            robottemplate_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of RobotTemplate, allocate an
            // array of trigger pointers for downstream reactions through port RobotTemplate.robot.drive
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robottemplate_self[src_runtime]->base.allocations); 
            robottemplate_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)] and RobotTemplate.robot.drive(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotTemplate.robot.drive(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotTemplate.robot.drive's trigger struct.
                robottemplate_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_robot_self[dst_runtime]->_lf__drive;
            }
        }
    }
    // **** Start non-nested deferred initialize for RobotTemplate.robot
    // For reference counting, set num_destinations for port RobotTemplate.robot.notify.
    // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        robottemplate_robot_self[src_runtime]->_lf_notify.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of RobotTemplate.robot triggers 1 downstream reactions
            // through port RobotTemplate.robot.notify.
            robottemplate_robot_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of RobotTemplate.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotTemplate.robot.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robottemplate_robot_self[src_runtime]->base.allocations); 
            robottemplate_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)] and RobotTemplate.display.message(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotTemplate.display.message(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotTemplate.display.message's trigger struct.
                robottemplate_robot_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_display_self[dst_runtime]->_lf__message;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of RobotTemplate.robot triggers 1 downstream reactions
            // through port RobotTemplate.robot.notify.
            robottemplate_robot_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of RobotTemplate.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotTemplate.robot.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robottemplate_robot_self[src_runtime]->base.allocations); 
            robottemplate_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)] and RobotTemplate.display.message(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotTemplate.display.message(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotTemplate.display.message's trigger struct.
                robottemplate_robot_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_display_self[dst_runtime]->_lf__message;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 2 of RobotTemplate.robot triggers 1 downstream reactions
            // through port RobotTemplate.robot.notify.
            robottemplate_robot_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 2 of RobotTemplate.robot, allocate an
            // array of trigger pointers for downstream reactions through port RobotTemplate.robot.notify
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &robottemplate_robot_self[src_runtime]->base.allocations); 
            robottemplate_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)] and RobotTemplate.display.message(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range RobotTemplate.display.message(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port RobotTemplate.display.message's trigger struct.
                robottemplate_robot_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &robottemplate_display_self[dst_runtime]->_lf__message;
            }
        }
    }
    // **** End of non-nested deferred initialize for RobotTemplate.robot
    // **** Start non-nested deferred initialize for RobotTemplate.display
    // **** End of non-nested deferred initialize for RobotTemplate.display
    // **** End of non-nested deferred initialize for RobotTemplate
    // Connect inputs and outputs for reactor RobotTemplate.
    // Connect inputs and outputs for reactor RobotTemplate.robot.
    // Connect RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)] to port RobotTemplate.robot.drive(0,1)
    // Iterate over ranges RobotTemplate.robot.drive(0,1)->[RobotTemplate.robot.drive(0,1)] and RobotTemplate.robot.drive(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotTemplate.robot.drive(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robottemplate_robot_self[dst_runtime]->_lf_drive = (robot_drive_t*)&robottemplate_self[src_runtime]->_lf_robot.drive;
        }
    }
    // Connect RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)] to port RobotTemplate.display.message(0,1)
    // Iterate over ranges RobotTemplate.robot.notify(0,1)->[RobotTemplate.display.message(0,1)] and RobotTemplate.display.message(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range RobotTemplate.display.message(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            robottemplate_display_self[dst_runtime]->_lf_message = (display_message_t*)&robottemplate_robot_self[src_runtime]->_lf_notify;
        }
    }
    // Connect inputs and outputs for reactor RobotTemplate.display.
    {
    }
    {
    }
    // Add port RobotTemplate.robot.drive to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &robottemplate_self[0]->_lf_robot.drive.is_present;
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port RobotTemplate.robot.notify to array of is_present fields.
            _lf_is_present_fields[1 + count] = &robottemplate_robot_self[0]->_lf_notify.is_present;
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance RobotTemplate
    {
        robottemplate_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        robottemplate_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        // Set reaction priorities for ReactorInstance RobotTemplate.robot
        {
            robottemplate_robot_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            robottemplate_robot_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            robottemplate_robot_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            robottemplate_robot_self[0]->_lf__reaction_1.index = 0x7fffffffffff0001LL;
            robottemplate_robot_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 140737488355327 shifted left 16 bits.
            robottemplate_robot_self[0]->_lf__reaction_2.index = 0x7fffffffffff0002LL;
        }
        // Set reaction priorities for ReactorInstance RobotTemplate.display
        {
            robottemplate_display_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            robottemplate_display_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            robottemplate_display_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 140737488355327 shifted left 16 bits.
            robottemplate_display_self[0]->_lf__reaction_1.index = 0x7fffffffffff0003LL;
        }
    }
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            if (_lf_startup_reactions[i]->mode != NULL) {
                // Skip reactions in modes
                continue;
            }
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
    _lf_handle_mode_startup_reset_reactions(
        _lf_startup_reactions, _lf_startup_reactions_size,
        NULL, 0,
        _lf_modal_reactor_states, _lf_modal_reactor_states_size);
}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }

}
void logical_tag_complete(tag_t tag_to_send) {

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
void terminate_execution() {}
void _lf_initialize_modes() {
    _lf_initialize_mode_states(
        _lf_modal_reactor_states, 
        _lf_modal_reactor_states_size);
}
void _lf_handle_mode_changes() {
    _lf_process_mode_changes(
        _lf_modal_reactor_states, 
        _lf_modal_reactor_states_size, 
        NULL, 
        0, 
        _lf_timer_triggers, 
        _lf_timer_triggers_size
    );
}
void _lf_handle_mode_triggered_reactions() {
    _lf_handle_mode_startup_reset_reactions(
        _lf_startup_reactions, _lf_startup_reactions_size,
        NULL, 0,
        _lf_modal_reactor_states, _lf_modal_reactor_states_size);
}
